apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    chart: kafka
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 30.1.4
    helm:
      releaseName: kafka
      valuesObject:
        listeners:
          client:
            protocol: PLAINTEXT
          controller:
            protocol: PLAINTEXT
          interbroker:
            protocol: PLAINTEXT
          external:
            protocol: PLAINTEXT
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd