apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtt-userregistrationrequested
  namespace: argocd
spec:
  project: default
  source:
    chart: marvel-top-trumps-user-registration-requested
    repoURL: https://github.com/TehMaxwell/mtt-backend-user-registration.git
    targetRevision: 0.4.1
    helm:
      releaseName: mtt-userregistrationrequested
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd