apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtt-userregistrationrequested
  labels:
    app: mtt-userregistrationrequested
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtt-userregistrationrequested
  template:
    metadata:
      labels:
        app: mtt-userregistrationrequested
    spec:
      containers:
      - name: mtt-userregistrationrequested
        image: ghcr.io/tehmaxwell/mtt-backend-user-registration:main
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        env:
          - name: "Topics__ConsumerTopic"
            value: "user-registration-requested"
          - name: "Topics__ProducerTopic"
            value: "user-registration-completed"
          - name: "ProducerConfiguration__BootstrapServers"
            value: "kafka.kafka:9092"
          - name: "ConsumerConfiguration__BootstrapServers"
            value: "kafka.kafka:9092"
          - name: "ConsumerConfiguration__GroupId"
            value: "user-registration-group"
          - name: "ConsumerConfiguration__AutoOffsetReset"
            value: "Earliest"
          - name: "ConsumerConfiguration__EnableAutoCommit"
            value: "true"
